name: Matrix
on: push
jobs:
  node-version-setup:
    runs-on: ubuntu-latest
    steps:
      - name: log-node-v
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: '6'
      - name: log-node-v
        run: node -v
