name: Slack Demo Salt
on: push
env:
    SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
jobs:
    log-env:
        runs-on: ubuntu-latest
        steps:
            - name: Pipeline_complete
              id: pipe
              uses: act10ns/slack@v1
              with:
                  status: ${{job.status}}
              if: always()
            - name: break
              run: echo hellllll
            - uses: act10ns/slack@v1
              name: steps1
              id: steps
              with:
                  status: ${{ job.status }}
                  steps: ${{ toJson(steps) }}
              if: always()
