name: Slack Demo Salt v2
on: push
env:
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
jobs:
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack again and again
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C0166RR1AJV\",\"text\":\"Hello world\"}'
