name: docker
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:14.4.0-alpine3.12
    steps:
      - name: log Node
        run: |
          npm -v
          cat /etc/os-release

